server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://49.234.92.136:3306/chen?serverTimezone=GMT%2B8
    username: root
    password: Cjd123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml

spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp