package com.chen.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table kt_examination
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class KtExamination implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kt_examination.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   试卷创建者用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kt_examination.userId
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     * Database Column Remarks:
     *   试卷名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kt_examination.examinationName
     *
     * @mbg.generated
     */
    private String examinationname;

    /**
     * Database Column Remarks:
     *   状态（1、未激活、2、已激活、3、已删除）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kt_examination.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * Database Column Remarks:
     *   该试卷考试时长限制  单位为:分钟
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kt_examination.duration
     *
     * @mbg.generated
     */
    private Integer duration;

    /**
     * Database Column Remarks:
     *   试卷二维码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kt_examination.QRcode
     *
     * @mbg.generated
     */
    private String qrcode;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kt_examination.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * Database Column Remarks:
     *   试卷类型（1：固定卷；2：随机卷）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kt_examination.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * Database Column Remarks:
     *   所属企业ID（其中1代表课通天下平台,2好班掌）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kt_examination.enterpriseId
     *
     * @mbg.generated
     */
    private Long enterpriseid;

    /**
     * Database Column Remarks:
     *   平台类型 ORG （机构）,ENTERPRISE（学习平台）,ROMAN（好班掌）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kt_examination.enterpriseType
     *
     * @mbg.generated
     */
    private String enterprisetype;

    /**
     * Database Column Remarks:
     *   参与次数上线
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kt_examination.upperlimit
     *
     * @mbg.generated
     */
    private Integer upperlimit;

    /**
     * Database Column Remarks:
     *   及格率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kt_examination.pass_rate
     *
     * @mbg.generated
     */
    private Integer passRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kt_examination
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kt_examination.id
     *
     * @return the value of kt_examination.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kt_examination.id
     *
     * @param id the value for kt_examination.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kt_examination.userId
     *
     * @return the value of kt_examination.userId
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kt_examination.userId
     *
     * @param userid the value for kt_examination.userId
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kt_examination.examinationName
     *
     * @return the value of kt_examination.examinationName
     *
     * @mbg.generated
     */
    public String getExaminationname() {
        return examinationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kt_examination.examinationName
     *
     * @param examinationname the value for kt_examination.examinationName
     *
     * @mbg.generated
     */
    public void setExaminationname(String examinationname) {
        this.examinationname = examinationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kt_examination.state
     *
     * @return the value of kt_examination.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kt_examination.state
     *
     * @param state the value for kt_examination.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kt_examination.duration
     *
     * @return the value of kt_examination.duration
     *
     * @mbg.generated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kt_examination.duration
     *
     * @param duration the value for kt_examination.duration
     *
     * @mbg.generated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kt_examination.QRcode
     *
     * @return the value of kt_examination.QRcode
     *
     * @mbg.generated
     */
    public String getQrcode() {
        return qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kt_examination.QRcode
     *
     * @param qrcode the value for kt_examination.QRcode
     *
     * @mbg.generated
     */
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kt_examination.createTime
     *
     * @return the value of kt_examination.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kt_examination.createTime
     *
     * @param createtime the value for kt_examination.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kt_examination.type
     *
     * @return the value of kt_examination.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kt_examination.type
     *
     * @param type the value for kt_examination.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kt_examination.enterpriseId
     *
     * @return the value of kt_examination.enterpriseId
     *
     * @mbg.generated
     */
    public Long getEnterpriseid() {
        return enterpriseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kt_examination.enterpriseId
     *
     * @param enterpriseid the value for kt_examination.enterpriseId
     *
     * @mbg.generated
     */
    public void setEnterpriseid(Long enterpriseid) {
        this.enterpriseid = enterpriseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kt_examination.enterpriseType
     *
     * @return the value of kt_examination.enterpriseType
     *
     * @mbg.generated
     */
    public String getEnterprisetype() {
        return enterprisetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kt_examination.enterpriseType
     *
     * @param enterprisetype the value for kt_examination.enterpriseType
     *
     * @mbg.generated
     */
    public void setEnterprisetype(String enterprisetype) {
        this.enterprisetype = enterprisetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kt_examination.upperlimit
     *
     * @return the value of kt_examination.upperlimit
     *
     * @mbg.generated
     */
    public Integer getUpperlimit() {
        return upperlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kt_examination.upperlimit
     *
     * @param upperlimit the value for kt_examination.upperlimit
     *
     * @mbg.generated
     */
    public void setUpperlimit(Integer upperlimit) {
        this.upperlimit = upperlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kt_examination.pass_rate
     *
     * @return the value of kt_examination.pass_rate
     *
     * @mbg.generated
     */
    public Integer getPassRate() {
        return passRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kt_examination.pass_rate
     *
     * @param passRate the value for kt_examination.pass_rate
     *
     * @mbg.generated
     */
    public void setPassRate(Integer passRate) {
        this.passRate = passRate;
    }
}