package com.chen.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table kttx_plan_message_enterprise_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class KttxPlanMessageEnterpriseUser implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kttx_plan_message_enterprise_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   PLAN-计划通知；STARTCOURAE-开课通知;ADMINSTARTCOURAE -管理员开课通知;HOMEWORK-作业通知；UPDATESTARTTIME-更开开课时间；CANCELCOURAE取消开课通知
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kttx_plan_message_enterprise_user.referType
     *
     * @mbg.generated
     */
    private String refertype;

    /**
     * Database Column Remarks:
     *   消息关联ID；课程ID、计划ID、作业ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kttx_plan_message_enterprise_user.referId
     *
     * @mbg.generated
     */
    private String referid;

    /**
     * Database Column Remarks:
     *   平台id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kttx_plan_message_enterprise_user.enterpriseId
     *
     * @mbg.generated
     */
    private Long enterpriseid;

    /**
     * Database Column Remarks:
     *   登录读取消息用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kttx_plan_message_enterprise_user.userId
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kttx_plan_message_enterprise_user.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kttx_plan_message_enterprise_user.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * Database Column Remarks:
     *   开课开始时间字段，用于开课变更通知
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kttx_plan_message_enterprise_user.courseStartTime
     *
     * @mbg.generated
     */
    private Date coursestarttime;

    /**
     * Database Column Remarks:
     *   开课结束时间字段，用于开课变更通知
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kttx_plan_message_enterprise_user.courseEndTime
     *
     * @mbg.generated
     */
    private Date courseendtime;

    /**
     * Database Column Remarks:
     *   开课地点，用于开课变更通知
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kttx_plan_message_enterprise_user.courseCity
     *
     * @mbg.generated
     */
    private String coursecity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kttx_plan_message_enterprise_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kttx_plan_message_enterprise_user.id
     *
     * @return the value of kttx_plan_message_enterprise_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kttx_plan_message_enterprise_user.id
     *
     * @param id the value for kttx_plan_message_enterprise_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kttx_plan_message_enterprise_user.referType
     *
     * @return the value of kttx_plan_message_enterprise_user.referType
     *
     * @mbg.generated
     */
    public String getRefertype() {
        return refertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kttx_plan_message_enterprise_user.referType
     *
     * @param refertype the value for kttx_plan_message_enterprise_user.referType
     *
     * @mbg.generated
     */
    public void setRefertype(String refertype) {
        this.refertype = refertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kttx_plan_message_enterprise_user.referId
     *
     * @return the value of kttx_plan_message_enterprise_user.referId
     *
     * @mbg.generated
     */
    public String getReferid() {
        return referid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kttx_plan_message_enterprise_user.referId
     *
     * @param referid the value for kttx_plan_message_enterprise_user.referId
     *
     * @mbg.generated
     */
    public void setReferid(String referid) {
        this.referid = referid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kttx_plan_message_enterprise_user.enterpriseId
     *
     * @return the value of kttx_plan_message_enterprise_user.enterpriseId
     *
     * @mbg.generated
     */
    public Long getEnterpriseid() {
        return enterpriseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kttx_plan_message_enterprise_user.enterpriseId
     *
     * @param enterpriseid the value for kttx_plan_message_enterprise_user.enterpriseId
     *
     * @mbg.generated
     */
    public void setEnterpriseid(Long enterpriseid) {
        this.enterpriseid = enterpriseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kttx_plan_message_enterprise_user.userId
     *
     * @return the value of kttx_plan_message_enterprise_user.userId
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kttx_plan_message_enterprise_user.userId
     *
     * @param userid the value for kttx_plan_message_enterprise_user.userId
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kttx_plan_message_enterprise_user.updateTime
     *
     * @return the value of kttx_plan_message_enterprise_user.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kttx_plan_message_enterprise_user.updateTime
     *
     * @param updatetime the value for kttx_plan_message_enterprise_user.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kttx_plan_message_enterprise_user.createTime
     *
     * @return the value of kttx_plan_message_enterprise_user.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kttx_plan_message_enterprise_user.createTime
     *
     * @param createtime the value for kttx_plan_message_enterprise_user.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kttx_plan_message_enterprise_user.courseStartTime
     *
     * @return the value of kttx_plan_message_enterprise_user.courseStartTime
     *
     * @mbg.generated
     */
    public Date getCoursestarttime() {
        return coursestarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kttx_plan_message_enterprise_user.courseStartTime
     *
     * @param coursestarttime the value for kttx_plan_message_enterprise_user.courseStartTime
     *
     * @mbg.generated
     */
    public void setCoursestarttime(Date coursestarttime) {
        this.coursestarttime = coursestarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kttx_plan_message_enterprise_user.courseEndTime
     *
     * @return the value of kttx_plan_message_enterprise_user.courseEndTime
     *
     * @mbg.generated
     */
    public Date getCourseendtime() {
        return courseendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kttx_plan_message_enterprise_user.courseEndTime
     *
     * @param courseendtime the value for kttx_plan_message_enterprise_user.courseEndTime
     *
     * @mbg.generated
     */
    public void setCourseendtime(Date courseendtime) {
        this.courseendtime = courseendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kttx_plan_message_enterprise_user.courseCity
     *
     * @return the value of kttx_plan_message_enterprise_user.courseCity
     *
     * @mbg.generated
     */
    public String getCoursecity() {
        return coursecity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kttx_plan_message_enterprise_user.courseCity
     *
     * @param coursecity the value for kttx_plan_message_enterprise_user.courseCity
     *
     * @mbg.generated
     */
    public void setCoursecity(String coursecity) {
        this.coursecity = coursecity;
    }
}