package com.chen.mapper;

import com.chen.entity.KtExamination;
import com.chen.entity.KtExaminationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KtExaminationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kt_examination
     *
     * @mbg.generated
     */
    long countByExample(KtExaminationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kt_examination
     *
     * @mbg.generated
     */
    int deleteByExample(KtExaminationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kt_examination
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kt_examination
     *
     * @mbg.generated
     */
    int insert(KtExamination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kt_examination
     *
     * @mbg.generated
     */
    int insertSelective(KtExamination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kt_examination
     *
     * @mbg.generated
     */
    List<KtExamination> selectByExample(KtExaminationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kt_examination
     *
     * @mbg.generated
     */
    KtExamination selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kt_examination
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KtExamination record, @Param("example") KtExaminationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kt_examination
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KtExamination record, @Param("example") KtExaminationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kt_examination
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KtExamination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kt_examination
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KtExamination record);
}