package com.chen.mapper;

import com.chen.entity.KttxPlanMessageEnterpriseUser;
import com.chen.entity.KttxPlanMessageEnterpriseUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KttxPlanMessageEnterpriseUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kttx_plan_message_enterprise_user
     *
     * @mbg.generated
     */
    long countByExample(KttxPlanMessageEnterpriseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kttx_plan_message_enterprise_user
     *
     * @mbg.generated
     */
    int deleteByExample(KttxPlanMessageEnterpriseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kttx_plan_message_enterprise_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kttx_plan_message_enterprise_user
     *
     * @mbg.generated
     */
    int insert(KttxPlanMessageEnterpriseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kttx_plan_message_enterprise_user
     *
     * @mbg.generated
     */
    int insertSelective(KttxPlanMessageEnterpriseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kttx_plan_message_enterprise_user
     *
     * @mbg.generated
     */
    List<KttxPlanMessageEnterpriseUser> selectByExample(KttxPlanMessageEnterpriseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kttx_plan_message_enterprise_user
     *
     * @mbg.generated
     */
    KttxPlanMessageEnterpriseUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kttx_plan_message_enterprise_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KttxPlanMessageEnterpriseUser record, @Param("example") KttxPlanMessageEnterpriseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kttx_plan_message_enterprise_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KttxPlanMessageEnterpriseUser record, @Param("example") KttxPlanMessageEnterpriseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kttx_plan_message_enterprise_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KttxPlanMessageEnterpriseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kttx_plan_message_enterprise_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KttxPlanMessageEnterpriseUser record);
}